"use client";

import { useState, useEffect } from "react";
import api from "@/app/lib/axios";
import { financeService } from "../service";

export default function AddTransactionModal({ isOpen, onClose, onSuccess }) {
  const [formData, setFormData] = useState({
    amount: "",
    transactionType: "INCOME", // Default
    transactionCategory: "SALE",
    paymentMethod: "CASH",
    notes: "",
    inventoryId: "",
  });
  
  const [inventories, setInventories] = useState([]);
  const [loading, setLoading] = useState(false);
  const baseURL = api.defaults.baseURL;

  useEffect(() => {
    if (isOpen) {
      // Fetch inventory items for dropdown
      const fetchInventory = async () => {
        try {
          // Adjust this endpoint if necessary based on existing inventory service
          const res = await api.get(`${baseURL}/inventory-management`);
          if (res.data && res.data.data) {
             setInventories(res.data.data);
          }
        } catch (err) {
          console.error("Failed to fetch inventory items", err);
        }
      };
      fetchInventory();
    }
  }, [isOpen]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    
    // Validate amount
    if (!formData.amount || Number(formData.amount) <= 0) {
      alert("Please enter a valid amount");
      setLoading(false);
      return;
    }

    try {
      const payload = {
        ...formData,
        amount: Number(formData.amount),
        // Ensure inventoryId is undefined if empty string, or backend logic handles it? 
        // Backend says: "If inventoryId is an empty string or null, we treat it as undefined" in service,
        // but let's send null if empty just in case or keep as is if backend handles ''
        inventoryId: formData.inventoryId || undefined, 
        // We need a dummy transactionId string as per DTO 'transactionId' field?
        // Wait, DTO says: @IsNotEmpty() @IsString() transactionId: string;
        // This seems odd. Usually transactionId is generated by backend. 
        // Checking backend schema: model Finnace { id String @id ... }
        // DTO: transactionId: string
        // Service: const { inventoryId, amount, ...rest } = createFinanceDto;
        // prisma.finnace.create({ data: { ...rest } })
        // The schema has `transactionId String`. Wait, let me check schema again.
        // `model Finnace { ... transactionId String ... }`
        // Is `transactionId` a foreign key or just a reference string? 
        // It looks like a manual string field in the schema provided by user.
        // "transactionId String" is in `Finnace` model. And there is NO `@relation` to another table using it?
        // Ah, `inventoryId` relates to `InventoryManagement`.
        // `transactionId` seems to be an arbitrary ID, maybe for external ref?
        // I will generate a random UUID or unique string for it if the user doesn't provide one, or ask the user to input it.
        // Since it's "transactionId", maybe it's the ID of the transaction itself? But `id` is `@default(uuid())`.
        // Maybe it is intended to be a manual receipt number?
        // I'll auto-generate a short ID for now or leave it empty if possible?
        // DTO says `@IsNotEmpty()`. So I MUST provide it.
        // I'll add a random string generator for now to satisfy the backend.
        transactionId: `TXN-${Date.now()}` 
      };

      await financeService.createTransaction(payload);
      alert("Transaction recorded successfully!");
      onSuccess();
    } catch (error) {
      console.error(error);
      alert(error.response?.data?.message || "Failed to create transaction");
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="modal modal-open">
      <div className="modal-box w-11/12 max-w-3xl">
        <h3 className="font-bold text-lg mb-4">Record New Transaction</h3>
        
        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            
            {/* Amount */}
            <div className="form-control w-full">
              <label className="label"><span className="label-text">Amount (৳)</span></label>
              <input 
                type="number" 
                name="amount" 
                value={formData.amount} 
                onChange={handleChange} 
                className="input input-bordered w-full" 
                placeholder="0.00" 
                step="0.01"
                required 
              />
            </div>

            {/* Type */}
            <div className="form-control w-full">
              <label className="label"><span className="label-text">Transaction Type</span></label>
              <select 
                name="transactionType" 
                value={formData.transactionType} 
                onChange={handleChange} 
                className="select select-bordered w-full"
              >
                <option value="INCOME">Income</option>
                <option value="EXPENSE">Expense</option>
              </select>
            </div>

            {/* Category */}
            <div className="form-control w-full">
              <label className="label"><span className="label-text">Category</span></label>
              <select 
                name="transactionCategory" 
                value={formData.transactionCategory} 
                onChange={handleChange} 
                className="select select-bordered w-full"
              >
                <option value="SALE">Sale</option>
                <option value="PURCHASE">Purchase</option>
                <option value="RETURN">Return</option>
                <option value="DAMAGE">Damage</option>
                <option value="ADJUSTMENT">Adjustment</option>
                <option value="SALARY">Salary</option>
                <option value="RENT">Rent</option>
                <option value="UTILITIES">Utilities</option>
                <option value="MAINTENANCE">Maintenance</option>
                <option value="LOGISTICS">Logistics</option>
                <option value="OTHER">Other</option>
              </select>
            </div>

            {/* Payment Method */}
            <div className="form-control w-full">
              <label className="label"><span className="label-text">Payment Method</span></label>
              <select 
                name="paymentMethod" 
                value={formData.paymentMethod} 
                onChange={handleChange} 
                className="select select-bordered w-full"
              >
                <option value="CASH">Cash</option>
                <option value="CREDIT_CARD">Credit Card</option>
                <option value="BANK_TRANSFER">Bank Transfer</option>
                <option value="MOBILE_PAYMENT">Mobile Payment</option>
              </select>
            </div>

            {/* Inventory Link (Optional) */}
             <div className="form-control w-full">
              <label className="label"><span className="label-text">Link Inventory (Optional)</span></label>
              <select 
                name="inventoryId" 
                value={formData.inventoryId} 
                onChange={handleChange} 
                className="select select-bordered w-full"
              >
                <option value="">-- No Inventory Linked --</option>
                {inventories.map(inv => (
                  <option key={inv.id} value={inv.id}>{inv.name}</option>
                ))}
              </select>
            </div>

          </div>

          {/* Notes */}
          <div className="form-control w-full mt-4">
            <label className="label"><span className="label-text">Notes</span></label>
            <textarea 
              name="notes" 
              value={formData.notes} 
              onChange={handleChange} 
              className="textarea textarea-bordered h-24" 
              placeholder="Additional details..."
            ></textarea>
          </div>

          <div className="modal-action">
            <button type="button" className="btn" onClick={onClose}>Cancel</button>
            <button 
              type="submit" 
              className={`btn text-white ${formData.transactionType === 'INCOME' ? 'btn-success' : 'btn-error'}`}
              disabled={loading}
            >
              {loading ? "Saving..." : "Save Transaction"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
